//! Autogenerated weights for pallet_assettokenization
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI.
//! Placeholder values are used — regenerate with actual hardware benchmarks.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_assettokenization.
pub trait WeightInfo {
    fn mint_asset() -> Weight;
    fn sign_contract() -> Weight;
    fn update_contract() -> Weight;
    fn freeze_asset() -> Weight;
    fn transfer_asset() -> Weight;
}

/// Weights for pallet_assettokenization using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: NextAssetId (r:1 w:1), Assets (r:0 w:1), AssetOwner (r:0 w:1)
    fn mint_asset() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: Assets (r:1 w:0), FrozenAssets (r:1 w:0), ContractSignatures (r:1 w:1)
    fn sign_contract() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: FrozenAssets (r:1 w:0), AssetOwner (r:1 w:0), Assets (r:1 w:1)
    fn update_contract() -> Weight {
        Weight::from_parts(22_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: Assets (r:1 w:0), AssetOwner (r:1 w:0), FrozenAssets (r:1 w:1)
    fn freeze_asset() -> Weight {
        Weight::from_parts(18_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: Assets (r:1 w:0), AssetOwner (r:1 w:1), ContractSignatures (r:1 w:0)
    fn transfer_asset() -> Weight {
        Weight::from_parts(22_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    fn mint_asset() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn sign_contract() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn update_contract() -> Weight {
        Weight::from_parts(22_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn freeze_asset() -> Weight {
        Weight::from_parts(18_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    /// Storage: Assets (r:1 w:0), AssetOwner (r:1 w:1), ContractSignatures (r:1 w:0)
    fn transfer_asset() -> Weight {
        Weight::from_parts(22_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
